src/utils.js

Common practise in translations is adding non-breakable spaces (&nbsp;). I would like to have them treated as any other HTML content in translation files.

Added support for HTML entities

---

src/index.js.flow

```
Error: node_modules/react-localize-redux/lib/index.js.flow:13
13: import type { LocalizeStateProps as _LocalizeStateProps } from './localize'; 
./localize. Required module not found
```

fixed syntax error, use "./Localize" in import instead "./localize"

---

docs/getting-started.md

Added import of function getActiveLanguage to code example cause this throws an undefined error when not properly imported.

Update Section 5. Translate components

---

docs/api/action-creators.md
docs/getting-started.md

Fixed broken link "pass multiple translations to components" in getting-started.md
Fixed typo `transaltion`

Fixed broken link "pass multiple translations to components"

---

src/Localize.js
tests/Localize.test.js

This solves the issue in #49 by checking whether the state object is a Map. What this PR does not cover is using Immutable JS without combineReducers, however I think this is a more specialised case and would be best handled as an extension of some kind, or a forked version of the project.
I am new to Flow so you may want to look at annotating the state argument, I had a look at defining a Map containing a LocaleState object however Flow didn't seem to like it. It does not however complain when not defining a Map type, probably because Map is in most respects just an object. I am happy to look further into this.

Handle state objects which are Maps

---

src/Localize.js
src/locale.js
tests/Localize.test.js
tests/locale.test.js

An issue exists where If a user happens to `Localize` a component before active language is set an error would be thrown. 
This fix ensures that the error is not thrown if a user happens to `Localize` a component before they have dispatched `initialize` with their app's languages.

fix Localize undefined active language issue

---

docs/api/action-creators.md

Thank you for this library.
I noticed that this part is missing. I'm not sure if it is intentional or not, but here is a simple PR - feel free to close if it is intentional :)
In case you are wondering how I came across this 'hidden' feature:
I have requirements for both:
* an explicitly-defined default language and translations (fetched from external API resource)
* placeholder children for `Translate` for use in a test environment.
Therefore I wanted placeholders that I could query during tests without loading the actual full set of translations, but during normal usage I did not want these placeholders added to the fetched translations set.

Add ignoreTranslateChildren to docs.

---

src/Translate.js
tests/Translate.test.js

For https://github.com/ryandrewjohnson/react-localize-redux/issues/67#issuecomment-394076318
When two `Translate` components are declared in the same position in the tree (e.g. using a ternary to  switch between a 'Submit' and 'Please Select' button), the `addDefaultTranslation` is not called when the ternary conditions changes.
`addDefaultTranslation` is blocked if the state flag `hasAddedDefaultTranslation` is true. This flag is set once per component lifecycle, so changes to the `id` prop (which should cause it to re-run) always hit a `hasAddedDefaultTranslation: true` condition. This is because the component re-renders without going through the entire lifecycle.
It is not possible to alter where `addDefaultTranslation` is called, since it requires the `context` argument from the …

[v3] - Add default translate if id prop changes.

---

src/index.d.ts

I was having some conflict when using `withLocalize` in a TS project. I think it's due to the fact that `withLocalize` is typed to wrap and return `React.Component`, as opposed to `React.ComponentType`.
1. Changed `withLocalize` to wrap and return `React.ComponentType<P>`
2. Added the `ignoreTranslateChildren` option to `initialize`, which I believe should be in there.
[As you can see here](https://github.com/piotrwitek/react-redux-typescript-guide#reactcomponentp-s), `React.Component` refers to a stateful class component, whereas this function should be compatible with either stateful/stateless function components.

[v3] - Minor change for TS types

---

package-lock.json
src/LocalizeContext.js
src/Translate.js
src/localize.js
tests/Translate.test.js
tests/localize.test.js

For #89.
This change allows `ignoreTranslateChildren` to be passed in the `initialize()` call. It allows global setting of this flag, which determines whether or not `Translate` children should be added into the default language.
* In `LocalizeContext` I ran into issues with flow. Because `ignoreTranslateChildren` is optional in the `initialize()` options, but required in the context object, flow was complaining that a boolean or undefined cannot be assigned to a boolean. It did this even after my attempts to narrow the type, so the resulting logic is somewhat verbose. Any suggestions welcome (I'm not familiar with flow).
* I left a note in `Translate` regarding the logic that determines whether to proceed with `addDefaultTranslation` because the code might look unnecessarily complex. …

Initialize ignore translate

---

demo/src/Main.js
demo/src/translations/global.json
src/index.d.ts
src/localize.js
src/utils.js
tests/Translate.test.js
tests/utils.test.js

From #76.
Repeating the summary for posterity.
`templater()` would return a string with all the dynamic content filled in:
```javascript
const translation = 'Hello ${ name }'
const data = { name: 'Google' }
templater(translation, data) // 'Hello Google'
```
`getLocalizedElement` would check if the result of `templater()` has any HTML tags in it:
```javascript
const getLocalizedElement = (...args) => {
...
const translatedValues = templater(translations, data)
return renderInnerHtml && hasHtmlTags(translatedValues)
?  React.createElement('span', { dangerouslySetInnerHTML: { __html: translatedValues } })
: translatedValues
}
```
`templater()` returns a string if the dynamic content does not contain any values satisfying `React.isValidElement()`. Otherwise, it returns an array of …

Allow React components as dynamic data arguments

---

src/Translate.js
src/utils.js
tests/Translate.test.js
tests/utils.test.js

For #97 
This change implements a fix based on the solution described in the linked issue.
I added a helper to access values nested in objects. This is just to avoid verbose checks like:
```js
if (obj && obj.a && obj.a.b) return obj.a.b.c
// instead
const val = get(obj, 'a.b.c', 'fallback Value')
```
Inspired by `lodash.get`, but probably much simpler.
I added some logic to check if the defaultLanguage has gone from undefined to something. It looks a bit verbose but there is a need to check both `props.context` and `props.options` I think. @ryandrewjohnson I don't know if there is a need to address the case where the language changes from one language to another?
In `getTranslateWithContext()`, I amended the default language to better reflect how this value is arrived in real use.
As far …

Ensure that addDefaultTranslation gets called

---

src/index.d.ts

Both ComponentClass and Component should be imported from `react`. `react-redux` doesn't contain those two.

Import ComponentClass and Component

---

src/LocalizeProvider.js
src/index.d.ts
tests/LocalizeProvider.test.js

For #82.
Added an optional `getState()` prop to `LocalizeProvider`. If passed, it will be used to access `state.localize` instead of the default dot notation.
Note that the localize state itself is always a plain JS object, so there should be no need to consider any changes deeper than this.

Allow passing of custom getState function

---

src/utils.js
tests/utils.test.js

For #116.
The `templater` is supposed to replace the placeholder parts of the translation string with the interpolated data. It will skip over the parts of the translation string that are not placeholders. It does this by setting a `matched` variable with the interpolated data, or leaving it undefined if there is no interpolation needed. Currently it fails to detect if the interpolated data is falsy (`0`, `""`), and thus returns the literal string in the translation.
I have made it detect any data value except undefined, so you can pass `0` or an empty string in the data and have it render correctly.

Handle falsy values in data.

---

src/utils.js
tests/utils.test.js

This pull request is fixing a simple bug that prevent the option to have two or more patterns without any spaces between them without having to add spaces inside the curly braces:
examples of pattern this PR solves:
```js
"${num}/${total}"
"${value}${index}"
"${filename}.${ext}"
...
```
In the current code, it doesn't works because the `genericPlaceholderPattern` is too eager and split the patterns as one element (eg: `["${num}/${total}"]` instead of `["${num}", "/", "${total}"]`) then it changes the first value so we get only the equivalent of `${num}` if we keep my last example.
And indeed, they all can be solved like this:
```js
"${ num }/${ total }"
"${ value }${ index }"
"${ filename }.${ ext }"
...
```
but let's not limiting the options of your users ? 😉 
thanks in advance!

Fix too eager templater reg exp

---

src/LocalizeProvider.js
src/index.d.ts
src/localize.js
src/utils.js
tests/LocalizeProvider.test.js

Proposed fix for #125 and #103 both related to server side rendering.
The library currently doesn't work with server side rendering, as the initial context for LocalizeProvider has no values for `languages`, or `translations` until the `initialize` action is called. 
Since no the state changes triggered by the `initialize` action will be tracked on the server this results in the empty context. This causes issues when the server attempts to render components with translations, and results in errors being thrown because of missing languages, and translation data.
Allow for passing `initialize` payload as a prop to `LocalizeProvider`. If using server side rendering this would be the required way to `initialize`, and would need to be done on the server and the client.
**Example:**
```jsx
// …
```

add initialize prop to LocaizeProvider to support SSR

---

src/LocalizeProvider.js
src/utils.js

Remove left over redux references that are causing errors for those users not using redux.

remove redux references

---

src/LocalizeProvider.js
tests/LocalizeProvider.test.js

This addresses the 'provider initialization failure' in #135 .
When _both_ `store` and `initialize` are passed to `LocalizeProvider`, the store is not initialized with the passed payload.
If `initialize` is omitted, this problem does not occur because the `initialize()` function is called from userland (from the `withLocalize`-wrapped component). This explicitly dispatches the initialize action.
If `store` is omitted, this problem does not occur because there is already code to initialize the passed payload into `LocalizeProvider`'s state.
I have added a method that initializes the passed `store` with the passed `initialize` payload (if both are present), and call it in `componentDidMount`. Since there are more things happening in `componentDidMount` as a result of this, I extracted the …

Ensured that store from props is initialized with initialize from props.

---

src/index.d.ts

This PR is in reference to [Issue #69](https://github.com/ryandrewjohnson/react-localize-redux/issues/69) specifically [this comment](https://github.com/ryandrewjohnson/react-localize-redux/issues/69#issuecomment-448863314)
it expands the definition of the `localizeReducer` function to solve TS errors

updated typescript definition for localizeReducer function
